In [1]:
# 加载必备库文件
import numpy as np

import mxnet as mx
from mxnet import nd
from mxnet import init
from mxnet import gluon
from mxnet import autograd

from mxnet.gluon import nn

In [2]:
res18_blk_num  = [2, 2, 2,  2] # 不是 bottleneck
res50_blk_num  = [3, 4, 6,  3]
res101_blk_num = [3, 4, 23, 3]
res152_blk_num = [3, 8, 36, 3]

# 为了便于参数导入，变量名最好和 gluoncv 的变量名相同
class BottleneckV1b(gluon.HybridBlock):
    """res 基本模块"""
    def __init__(self, channels, strides, isdownsample=False, **kwargs):
        super(BottleneckV1b, self).__init__(**kwargs)
        # 一个 bottleneck 内， 1*1 卷积 channel 扩大的倍数
        self.expansion = 4
        self.isdownsample = isdownsample
        self.strides = strides

        
        # bottletneck 内总是 1*1 conv -- 3*3 conv -- 1*1 conv
        self.conv1 = nn.Conv2D(channels=channels, kernel_size=(1,1), strides=(1,1),
                               padding=(0,0), groups=1, use_bias=False)
        self.bn1   = nn.BatchNorm() # use_global_stats=True 默认为 False
        self.relu  = nn.Activation('relu')
        
        self.conv2 = nn.Conv2D(channels=channels, kernel_size=3, strides=self.strides,
                               padding=(1,1), groups=1, use_bias=False)
        self.bn2   = nn.BatchNorm()
        
        self.conv3 = nn.Conv2D(channels=channels * self.expansion, kernel_size=(1,1), strides=(1,1),
                               padding=(0,0), groups=1, use_bias=False)
        self.bn3   = nn.BatchNorm()
        
        if self.isdownsample:
            self.downsample = nn.HybridSequential()
            self.downsample.add(nn.Conv2D(channels=channels * self.expansion, kernel_size=(1,1), strides=self.strides,
                                         padding=(0,0), groups=1, use_bias=False),
                                nn.BatchNorm())


    def hybrid_forward(self, F, x):
        residual = self.relu(self.bn1(self.conv1(x)))
        residual = self.relu(self.bn2(self.conv2(residual)))
        residual = self.bn3(self.conv3(residual))

        if self.isdownsample:
            x = self.downsample(x)

        x = x + residual
        out = self.relu(x)

        return out


In [ ]:
net = BottleneckV1b(64, (2,2), isdownsample=True)
x = nd.random.uniform(shape=(1,1,224,224))
net.initialize(init.Xavier())
y = net(x)

In [3]:
class ResNet(gluon.HybridBlock):
    """ Pre-trained ResNetV1b Model, which produces the strides of 8
    featuremaps at conv5.

    Parameters
    ----------
    block : Block
        Class for the residual block. Options are BasicBlockV1, BottleneckV1.
    layers : list of int
        Numbers of layers in each block
    classes : int, default 1000
        Number of classification classes.
    norm_layer : object
        Normalization layer used (default: :class:`mxnet.gluon.nn.BatchNorm`)
        Can be :class:`mxnet.gluon.nn.BatchNorm` or :class:`mxnet.gluon.contrib.nn.SyncBatchNorm`.
    last_gamma : bool, default False
        Whether to initialize the gamma of the last BatchNorm layer in each bottleneck to zero.
    deep_stem : bool, default False
        Whether to replace the 7x7 conv1 with 3 3x3 convolution layers.
    avg_down : bool, default False
        Whether to use average pooling for projection skip connection between stages/downsample.
    final_drop : float, default 0.0
        Dropout ratio before the final classification layer.
    use_global_stats : bool, default False
        Whether forcing BatchNorm to use global statistics instead of minibatch statistics;
        optionally set to True if finetuning using ImageNet classification pretrained models.
    """
    # pylint: disable=unused-variable
    def __init__(self, block_nums, channels, strides, classes=1000, **kwargs):
        super(ResNet, self).__init__(**kwargs)

        self.features = nn.HybridSequential()
        self.features.add(nn.Conv2D(channels=64, kernel_size=(7,7), strides=(2,2),
                                    padding=(3,3), groups=1, use_bias=False))
        self.features.add(nn.BatchNorm())
        self.features.add(nn.Activation('relu'))
        self.features.add(nn.MaxPool2D(pool_size=(3,3), strides=(2,2), padding=(1,1)))
        
        # block_nums = [3, 4, 6, 3]
        # channels = [64, 128, 256, 512]
        # strides = [(1,1), (2,2), (2,2), (2,2)]
        for i in range(len(block_nums)):
            blk = nn.HybridSequential()
            for num in range(block_nums[i]) :
                if num == 0:
                    bottleneck = BottleneckV1b(channels[i], strides[i], isdownsample=True)
                else:
                    bottleneck = BottleneckV1b(channels[i], (1,1), isdownsample=False)
                blk.add(bottleneck)
            self.features.add(blk)

        self.avgpool = nn.GlobalAvgPool2D()
        self.out = nn.Dense(classes)

    def hybrid_forward(self, F, x):
        feature = self.features(x)
        out = self.avgpool(feature)
        out = self.out(out)
        return out

block_nums = [3, 4, 6, 3]
channels = [64, 128, 256, 512]
strides = [(1,1), (2,2), (2,2), (2,2)]

In [10]:
net = ResNet(block_nums, channels, strides)
x = nd.random.uniform(shape=(1,1,224,224))
net.initialize(init.Xavier())
y = net(x)

In [11]:
print(net)

ResNet(
  (features): HybridSequential(
    (0): Conv2D(1 -> 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=64)
    (2): Activation(relu)
    (3): MaxPool2D(size=(3, 3), stride=(2, 2), padding=(1, 1), ceil_mode=False)
    (4): HybridSequential(
      (0): BottleneckV1b(
        (conv1): Conv2D(64 -> 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=64)
        (relu): Activation(relu)
        (conv2): Conv2D(64 -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=64)
        (conv3): Conv2D(64 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_gl

In [90]:
def anchor_gen(ratios, scales, width, height, stride):
    """生成 anchor
    return (xmin, ymin, xmax, ymax)"""
    anchor = []
    for s in scales:
        for r in ratios:
            w = s / np.sqrt(r)
            w = np.round(w * 0.5)
            h = s * np.sqrt(r)
            h = np.round(h * 0.5)
            anchor.append([-w, -h, w, h])
            
    anchor = np.array(anchor)

    x = range(width)
    y = range(height)
    x, y = np.meshgrid(x, y)
    
    offsets = np.concatenate((x[:,:,np.newaxis], y[:,:,np.newaxis], x[:,:,np.newaxis], y[:,:,np.newaxis]), axis = -1)
    offsets *= stride
    #print(offsets.shape)
    #print(offsets)
    # 中心点需要向右下角偏移 stride // 2
    offsets += stride // 2
    #print(offsets)
    
    anchor = anchor.reshape(1, -1, 4) + offsets.reshape(-1,1,4)
    anchor = anchor.reshape(-1, 4)
    
    return anchor

ratios = [0.5, 1, 2]
scales = [32, 64, 128, 256, 512]

In [40]:
anchor = anchor_gen(ratios, scales, 600//16, 800//16, 16)

(50, 37, 4)
[[[  0   0   0   0]
  [ 16   0  16   0]
  [ 32   0  32   0]
  ..., 
  [544   0 544   0]
  [560   0 560   0]
  [576   0 576   0]]

 [[  0  16   0  16]
  [ 16  16  16  16]
  [ 32  16  32  16]
  ..., 
  [544  16 544  16]
  [560  16 560  16]
  [576  16 576  16]]

 [[  0  32   0  32]
  [ 16  32  16  32]
  [ 32  32  32  32]
  ..., 
  [544  32 544  32]
  [560  32 560  32]
  [576  32 576  32]]

 ..., 
 [[  0 752   0 752]
  [ 16 752  16 752]
  [ 32 752  32 752]
  ..., 
  [544 752 544 752]
  [560 752 560 752]
  [576 752 576 752]]

 [[  0 768   0 768]
  [ 16 768  16 768]
  [ 32 768  32 768]
  ..., 
  [544 768 544 768]
  [560 768 560 768]
  [576 768 576 768]]

 [[  0 784   0 784]
  [ 16 784  16 784]
  [ 32 784  32 784]
  ..., 
  [544 784 544 784]
  [560 784 560 784]
  [576 784 576 784]]]
[[[  8   8   8   8]
  [ 24   8  24   8]
  [ 40   8  40   8]
  ..., 
  [552   8 552   8]
  [568   8 568   8]
  [584   8 584   8]]

 [[  8  24   8  24]
  [ 24  24  24  24]
  [ 40  24  40  24]
  ..., 
  [

In [24]:
print(anchor.shape)
print(anchor[0])
print(anchor[1])
print(anchor[2])
print(anchor[3])
print(anchor[4])

(7200000, 4)
[-23. -11.  23.  11.]
[-16. -16.  16.  16.]
[-11. -23.  11.  23.]
[-45. -23.  45.  23.]
[-32. -32.  32.  32.]


In [77]:

def get_realbbox(bbox_pred, anchors, wh_max=4.42):
    """根据 anchor 得到预测边框的真实值
    bbox_pred, anchors 都是 numpy array 数据类型 (x, y, w, h) 形式，维度 (C,N,4)"""
    batch = bbox_pred.shape[0]

    x = bbox_pred[:,:,0] * anchors[:,:,2] + anchors[:,:,0]
    y = bbox_pred[:,:,1] * anchors[:,:,3] + anchors[:,:,1]
    w = anchors[:,:,2] * np.minimum(np.exp(bbox_pred[:,:,2]), wh_max)
    h = anchors[:,:,3] * np.minimum(np.exp(bbox_pred[:,:,3]), wh_max)

    return np.concatenate((x.reshape(batch,-1,1),y.reshape(batch,-1,1),
                           w.reshape(batch,-1,1),h.reshape(batch,-1,1)), axis=-1)

In [49]:
a = np.arange(16).reshape(2,2,4) * 0.1
b = np.arange(8).reshape(1,2,4) * 0.3
print(a)
print(b)
get_realbbox(a,b)

[[[ 0.   0.1  0.2  0.3]
  [ 0.4  0.5  0.6  0.7]]

 [[ 0.8  0.9  1.   1.1]
  [ 1.2  1.3  1.4  1.5]]]
[[[ 0.   0.3  0.6  0.9]
  [ 1.2  1.5  1.8  2.1]]]


array([[[ 0.        ,  0.39      ,  0.73284165,  1.21487293],
        [ 1.92      ,  2.55      ,  3.27981384,  4.22888069]],

       [[ 0.48      ,  1.11      ,  1.6309691 ,  2.70374942],
        [ 3.36      ,  4.23      ,  7.29935994,  9.282     ]]])

In [95]:
# batch 为 1 的处理函数
def get_realbbox2D(bbox_pred, anchors, wh_max=4.42):
    """根据 anchor 得到预测边框的真实值
    bbox_pred, anchors 都是 numpy array 数据类型 (x, y, w, h) 形式，维度 (N,4)"""
    print("bbox_pred", bbox_pred.shape)
    print("anchor", anchors.shape)

    x = bbox_pred[:,0] * anchors[:,2] + anchors[:,0]
    y = bbox_pred[:,1] * anchors[:,3] + anchors[:,1]
    w = anchors[:,2] * np.minimum(np.exp(bbox_pred[:,2]), wh_max)
    h = anchors[:,3] * np.minimum(np.exp(bbox_pred[:,3]), wh_max)

    return np.concatenate((x.reshape(-1,1),y.reshape(-1,1),
                           w.reshape(-1,1),h.reshape(-1,1)), axis=-1)

In [96]:
box = np.array([[[1,2,3,4],[2,3,4,5]]])
anchor = np.array([[[6,7,8,9],[1,2,5,6]]])
get_realbbox(box, anchor)

array([[[ 14.  ,  25.  ,  35.36,  39.78],
        [ 11.  ,  20.  ,  22.1 ,  26.52]]])

In [7]:
def bbox_clip_by_img(bbox, img):
    """bbox 形式 (x1, y1, x2, y2) 维度 (N,4)"""
    imgsize = img[-2:]
    print(imgsize)
    bbox[:,:2] = np.maximum(bbox[:,:2], 0)
    bbox[:,2] = np.minimum(bbox[:,2], imgsize[0])
    bbox[:,3] = np.minimum(bbox[:,3], imgsize[1])
    return bbox

In [106]:
def compute_iou(bbox_a, bbox_b):
    """计算两组 bounding boxes 的 Intersection-Over-Union(IOU)

    Parameters
    ----------
    bbox_a : numpy.ndarray
        shape (M, 4) . bbox 格式 (xmin,ymin,xmax,ymax)
    bbox_b : numpy.ndarray
        shape (N, 4) . bbox 格式 (xmin,ymin,xmax,ymax)

    Returns
    -------
    二维数组 shape (M,N) ，其中任意一个元素 (i,j) 表示 bboxa[i] 和 bboxb[j] 的 IoU

    """
    
    if bbox_a.shape[1] < 4 or bbox_b.shape[1] < 4:
        raise IndexError("Bounding boxes axis 1 must have at least length 4")

    tl = np.maximum(bbox_a[:, None, :2], bbox_b[:, :2])
    br = np.minimum(bbox_a[:, None, 2:4], bbox_b[:, 2:4])

    area_i = np.prod(br - tl, axis=2) * (tl < br).all(axis=2)
    area_a = np.prod(bbox_a[:, 2:4] - bbox_a[:, :2], axis=1)
    area_b = np.prod(bbox_b[:, 2:4] - bbox_b[:, :2], axis=1)
    return area_i / (area_a[:, None] + area_b - area_i)


# 依据 score 排序，从 score 最高第一个 box 开始，所有与该 box IOU 大于指定阈值的
# box 都会被删掉；同时把 box 加入到最终的队列中，并从原 list 中删除。
# 接着用队列中剩下的 score 最高的 box 去抑制队列中剩余的 box

# 可以先删掉 score 比较低的 box
def non_max_suppression(boxes, scores, topk=None, threshold=0.7):
    """执行 non-maximum suppression ，返回保留 boxes 的索引.
    boxes: [N, (y1, x1, y2, x2)]
    scores: 1-D array of box scores.
    threshold: Float. IoU 阈值，一般为 0.7
    """
    assert boxes.shape[0] > 0
    if boxes.dtype.kind != "f":
        boxes = boxes.astype(np.float32)

    # scores 从大到小排序
    ixs = scores.argsort()[::-1]
    if topk:
        ixs = ixs[:topk]
    #print("ixs", ixs)

    pick = []
    while len(ixs) > 0:
        # 每次都选择队列中 score 最高的 box ，加入最终结果，并用他抑制队列中剩余的 box
        i = ixs[0]
        pick.append(i)
        # Compute IoU of the picked box with the rest
        iou = compute_iou(boxes[i][np.newaxis,:], boxes[ixs[1:]])
        # Identify boxes with IoU over the threshold. This
        # returns indices into ixs[1:], so add 1 to get
        # indices into ixs.
        remove_ixs = np.where(iou > threshold)[1] + 1
        #print("remove_ixs", remove_ixs)
        # Remove indices of the picked and overlapped boxes.
        # 所有与 score 最高的 box IoU 大于阈值的 box 都从队列中移除
        ixs = np.delete(ixs, remove_ixs)
        ixs = np.delete(ixs, 0)
    #print("pick",pick)
    return np.array(pick, dtype=np.int32)

In [121]:
def proposal(anchor, score, bbox_pred, post_nms=300, img=[600,800], nms_threshold=0.3):
    """
    Generate proposals. Limit to batch-size=1 in current implementation.
    img = [600,800]
    """
    pre_nms  = 6000
    #post_nms = 300
    min_size = 60

    # 根据 anchor 得到 Bbox 的真实大小
    roi = get_realbbox2D(bbox_pred, anchor)

    # roi 不能超过图像的边界
    roi = bbox_clip_by_img(roi, img)

    # remove bounding boxes that don't meet the min_size constraint
    width  = roi[:,2] - roi[:,0]
    height = roi[:,3] - roi[:,1]
    print("width", width)
    print("height", height)
    invalid = (width < min_size) + (height < min_size)
    print("invalid", invalid)
    print("scores", score.shape)
    invalidindex = np.where(invalid!=0)
    score = np.delete(score, invalidindex)
    print("scores", score.shape)
    print("roi", roi.shape)
    roi = np.delete(roi, invalidindex, axis=0)
    
    print("roi", roi.shape)
    print("scores", score.shape)

    # Non-maximum suppression
    keepindex = non_max_suppression(roi, score, pre_nms, nms_threshold)
    
    print("keepindex", keepindex.shape)

    # 仅仅保留 post_nms 个数的 boxes
    if post_nms:
        keepindex = keepindex[:post_nms]

    print("keepindex", keepindex.shape)

    rpn_scores = score[keepindex]
    rpn_bbox = roi[keepindex,:]

    return rpn_scores, rpn_bbox


In [ ]:
anchor = np.array([[-23., -11.,  23.,  11.],                   
                [-16., -16.,  16.,  16.],
                [-11., -23.,  11.,  23.],
                [-21., -11.,  25.,  11.],
                [-14., -16.,  18.,  16.],
                [ -9., -23.,  13.,  23.],
                [-23.,  -9.,  23.,  13.],
                [-16., -14.,  16.,  18.],
                [-11., -21.,  11.,  25.],
                [-21.,  -9.,  25.,  13.],
                [-14., -14.,  18.,  18.],
                [ -9., -21.,  13.,  25.]])
print(anchor.shape)
score = np.array([0.8,0.2,0.4, 0.1,0.45,0.23, 0.45,0.21,0.93, 0.34,0.45,0.42])
print(score.shape)
bbox_pred = anchor + [1,2,3,4]

In [ ]:
proposal(anchor, score, bbox_pred)

In [ ]:
print(bbox_pred)

In [140]:
class FasterRcnn(gluon.HybridBlock):
    """res50 为 bone 的 faster r-cnn"""
    def __init__(self, class_num=80, **kwargs):
        super(FasterRcnn, self).__init__(**kwargs)        
        
        self.ratios = [0.5, 1, 2]
        self.scales = [32, 64, 128, 256, 512]
        self.anchor_depth = len(self.ratios) * len(self.scales) # gluoncv 中使用了 15 个 anchor
        self.rpn_channels = 1024
        self.roi_size = (14, 14)
        self.post_nms = 50 #300
        self.stride = 16
        
        self.class_num = class_num
        
        self.socre_thread = 0.01
        
        # 网络的 bone
        bone = ResNet(block_nums, channels, strides)
        #self.features = nn.HybridSequential()
        #self.features.add(bone.features[:7])
        self.features =bone.features[:7]
        #self.top_features = nn.HybridSequential()
        #self.top_features.add(bone.features[7:])
        self.top_features = bone.features[7:]
        
        self.global_avg_pool = nn.GlobalAvgPool2D()
        self.class_predictor = nn.Dense(self.class_num + 1)
        self.box_predictor = nn.Dense(self.class_num * 4)
        
        # RPN 网络
        self.rpn = nn.HybridSequential()
        self.rpn.add(nn.Conv2D(self.rpn_channels, 3, 1, 1))
        self.rpn.add(nn.Activation('relu'))
        # 使用了 sigmoid 而不是 softmax，减少通道的个数
        self.rpn_score = nn.Conv2D(self.anchor_depth, 1, 1, 0)
        self.rpn_loc = nn.Conv2D(self.anchor_depth * 4, 1, 1, 0)

        
    def hybrid_forward(self, F, x):
        feat = self.features(x)
        print("feat",feat.shape)
        width = 38
        height = 50
        
        # RPN
        anchor = anchor_gen(self.ratios, self.scales, width, height, self.stride)
        print("anchor", anchor.shape)
        rpn = self.rpn(feat)
        print("rpn", rpn.shape)
        raw_rpn_score = self.rpn_score(rpn).transpose(axes=(0, 2, 3, 1)).reshape((0, -1, 1))
        rpn_score = nd.sigmoid(raw_rpn_score)
        rpn_box_pred = self.rpn_loc(rpn).transpose(axes=(0, 2, 3, 1)).reshape((0, -1, 4))
        print("rpn_score", rpn_score.shape)
        print("rpn_box_pred", rpn_box_pred.shape)
        rpn_score, rpn_box = proposal(anchor, rpn_score.asnumpy(), np.squeeze(rpn_box_pred.asnumpy()), self.post_nms)
        rpn_score = nd.array(rpn_score)
        rpn_box = nd.array(rpn_box)
        
        # roi 开始增加 batchid 0
        rpn_box = rpn_box.reshape((-1, 4))
        roi_batchid = nd.zeros((self.post_nms, 1))
        #roi_batchid = nd.zeros((rpn_box.shape[0], 1))
        rpn_roi = nd.concat(*[roi_batchid.reshape((-1, 1)), rpn_box], dim=-1)
        
        # ROIPolling
        pooled_feat = nd.ROIPooling(feat, rpn_roi, self.roi_size, 1. / self.stride)
        print("pooled_feat",pooled_feat.shape)

        # RCNN prediction
        top_feat = self.top_features(pooled_feat)
        avg_feat = self.global_avg_pool(top_feat)
        cls_pred = self.class_predictor(avg_feat)
        box_pred = self.box_predictor(avg_feat)

        cls_pred = cls_pred.reshape((self.post_nms, self.class_num + 1))
        # 0 是背景的概率，只需要前景的即可
        scores = nd.softmax(cls_pred, axis=-1)[1:]
        box_pred = box_pred.reshape((self.post_nms, self.class_num, 4)).transpose((1,0,2))
        print("box_pred", box_pred.shape)
        print("rpn_box", rpn_box.shape)
        
        # 入参是 center 格式 TODO
        bbox = get_realbbox(box_pred.asnumpy(), rpn_box.reshape(1,-1,4).asnumpy(), wh_max=4.42)
        print("bbox", bbox.shape)


        # 剔除 score 小于 thread 的预测
        mask = scores > self.socre_thread
        
        ids = 1
        

        return ids, scores, bbox


In [133]:
net = FasterRcnn()
x = nd.random.uniform(shape=(1,1,600,800))
net.initialize(init.Xavier())
y = net(x)

feat (1, 1024, 38, 50)
anchor (28500, 4)
rpn (1, 1024, 38, 50)
rpn_score (1, 28500, 1)
rpn_box_pred (1, 28500, 4)
bbox_pred (28500, 4)
anchor (28500, 4)
[600, 800]
width [  30.68011671   24.04203987   19.37640738 ...,  309.05692963  251.44822371
  196.38676345]
height [  19.21793151   23.62950611   30.953435   ...,  165.06685226  263.83555083
  372.28306089]
invalid [ True  True  True ..., False False False]
scores (1, 28500, 1)
scores (17529,)
roi (28500, 4)
roi (17529, 4)
scores (17529,)
keepindex (157,)
keepindex (50,)
pooled_feat (50, 1024, 14, 14)
box_pred (80, 50, 4)
rpn_box (50, 4)
bbox (80, 50, 4)


In [145]:
net = FasterRcnn()
print(net)

FasterRcnn(
  (features): HybridSequential(
    (0): Conv2D(None -> 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
    (2): Activation(relu)
    (3): MaxPool2D(size=(3, 3), stride=(2, 2), padding=(1, 1), ceil_mode=False)
    (4): HybridSequential(
      (0): BottleneckV1b(
        (conv1): Conv2D(None -> 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        (relu): Activation(relu)
        (conv2): Conv2D(None -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        (conv3): Conv2D(None -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_

In [146]:
net.features.load_parameters("features.params")
net.top_features.load_parameters("topfeatures.params")
#net.global_avg_pool.load_parameters("global_avg_pool.params")
net.class_predictor.load_parameters("class_predictor.params")
net.box_predictor.load_parameters("box_predictor.params")
net.rpn.load_parameters("rpn_conv1.params")
net.rpn_score.load_parameters("rpn_score.params")
net.rpn_loc.load_parameters("rpn_loc.params")

In [147]:
x = nd.random.uniform(shape=(1,3,600,800))
y = net(x)

feat (1, 1024, 38, 50)
anchor (28500, 4)
rpn (1, 1024, 38, 50)
rpn_score (1, 28500, 1)
rpn_box_pred (1, 28500, 4)
bbox_pred (28500, 4)
anchor (28500, 4)
[600, 800]
width [  31.99918604   37.17669296   25.42470777 ...,  357.45069581  221.3213045
  179.91775751]
height [  17.52285933   20.98014021   29.72794467 ...,  243.87935047  269.08685261
  366.45209389]
invalid [ True  True  True ..., False False False]
scores (1, 28500, 1)
scores (18211,)
roi (28500, 4)
roi (18211, 4)
scores (18211,)
keepindex (101,)
keepindex (50,)
pooled_feat (50, 1024, 14, 14)
box_pred (80, 50, 4)
rpn_box (50, 4)
bbox (80, 50, 4)


In [148]:
print(net)

FasterRcnn(
  (features): HybridSequential(
    (0): Conv2D(3 -> 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=64)
    (2): Activation(relu)
    (3): MaxPool2D(size=(3, 3), stride=(2, 2), padding=(1, 1), ceil_mode=False)
    (4): HybridSequential(
      (0): BottleneckV1b(
        (conv1): Conv2D(64 -> 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=64)
        (relu): Activation(relu)
        (conv2): Conv2D(64 -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=64)
        (conv3): Conv2D(64 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, us

In [ ]:
def preprocessing_img(imgname, mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)):
    """图像 nominalize 
    测试的时候，transform 不需要额外的处理，只需要归一化以及将 BCWH -> 

    Parameters
    ----------
    imgs : string 
        待处理的图像名字
    mean : iterable of float
        Mean pixel values.
    std : iterable of float
        Standard deviations of pixel values.

    Returns
    -------
    网络的输入和 resize 后的图像

    """
    
    img = mx.image.imread(imgname)

    # 只能在 600*800 时 work
    img = mx.image.imresize(img, 600, 800)
    orig_img = img.asnumpy().astype('uint8')
    img = mx.nd.image.to_tensor(img)
    img = mx.nd.image.normalize(img, mean=mean, std=std)
    # img.expand_dims(0) 由 CHW -> BCHW
    return img.expand_dims(0), orig_img